version: "3.9"
services: 
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
  backend:
    build: ./backend
    ports:
      - "4001:4001"
  db:
    build: ./db
    ports:
      - "5432:5432"
