GET http://localhost:4001/users/all HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJIdWdvIiwibGFzdE5hbWUiOiJXaW50ZXIiLCJlbWFpbCI6Imh1Z28ud2ludGVyQGV4YW1wbGUuY29tIiwiY3JlYXRlZE9uIjoiMjAyMS0wNi0wN1QyMjowMDowMC4wMDBaIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjIzMTcyNzI3LCJleHAiOjE2MjMxNzI3ODd9.75Q_nMi-wGf0hw2mHk2VnSsfH9HFBKXnl30C0AQlJ9I

###

GET http://localhost:4001/users/getByEmail/hugo.winter@example.com HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJIdWdvIiwibGFzdE5hbWUiOiJXaW50ZXIiLCJlbWFpbCI6Imh1Z28ud2ludGVyQGV4YW1wbGUuY29tIiwiY3JlYXRlZE9uIjoiMjAyMS0wNi0wN1QyMjowMDowMC4wMDBaIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjIzMTcyNzI3LCJleHAiOjE2MjMxNzI3ODd9.75Q_nMi-wGf0hw2mHk2VnSsfH9HFBKXnl30C0AQlJ9I


###

POST http://localhost:4001/users/register HTTP/1.1
content-type: application/json

{
    "firstName": "Hugo",
    "lastName": "Winter",
    "email": "hugo.winter@example.com",
    "password": "Test1234"
}

###

POST http://localhost:4001/users/login HTTP/1.1
content-type: application/json

{
    "email": "hugo.winter@example.com",
    "password": "Test1234"
}

###

POST http://localhost:4001/users/verifyUser HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJIdWdvIiwibGFzdE5hbWUiOiJXaW50ZXIiLCJlbWFpbCI6Imh1Z28ud2ludGVyQGV4YW1wbGUuY29tIiwiY3JlYXRlZE9uIjoiMjAyMS0wNi0wN1QyMjowMDowMC4wMDBaIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjIzMTcyNzI3LCJleHAiOjE2MjMxNzI3ODd9.75Q_nMi-wGf0hw2mHk2VnSsfH9HFBKXnl30C0AQlJ9I

{
    "firstName": "Hugo",
    "lastName": "Winter",
    "email": "hugo.winter@example.com",
    "password": "Test1234",
    "createdOn": "2020-11-10T23:00:00.000Z"
}

###
