DROP TABLE IF EXISTS user_task;

DROP TABLE IF EXISTS project_task;

DROP TABLE IF EXISTS user_project;

DROP TABLE IF EXISTS proma_user;

DROP TABLE IF EXISTS role;

DROP TABLE IF EXISTS project;

DROP TABLE IF EXISTS task;

DROP TABLE IF EXISTS status;
